[font]
size = 25

[cursor.style]
shape    = "Beam"
blinking = "Always"

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
startup_mode = "Fullscreen"
decorations  = "none"

[window.padding]
x = 7
y = 0
